export const RealtimeEvents = {
  CONNECTION_READY: "connection:ready",
  NEED_ITEM_ADDED: "needs:itemAdded",
  NEED_ITEM_UPDATED: "needs:itemUpdated",
  NEED_ITEM_PURCHASED: "needs:itemPurchased",
  NEED_EXPENSE_CREATED: "needs:expenseCreated",
  CHORE_CREATED: "chores:created",
  CHORE_UPDATED: "chores:updated",
  CHORE_COMPLETED: "chores:completed",
  CHORE_ASSIGNED: "chores:assigned",
  CHORE_DELETED: "chores:deleted",
  EXPENSE_CREATED: "expenses:created",
  EXPENSE_BALANCE_UPDATED: "expenses:balanceUpdated",
  PAYMENT_RECORDED: "payments:recorded",
  NOTIFICATION_CREATED: "notifications:created",
  NOTIFICATION_READ: "notifications:read",
  NOTIFICATION_DELETED: "notifications:deleted",
  HOUSEHOLD_MEMBER_JOINED: "household:memberJoined",
  HOUSEHOLD_MEMBER_LEFT: "household:memberLeft",
  HOUSEHOLD_DELETED: "household:deleted",
} as const;

export const EventQueryKeys: Record<string, string[][]> = {
  [RealtimeEvents.NEED_ITEM_ADDED]: [["needs"]],
  [RealtimeEvents.NEED_ITEM_UPDATED]: [["needs"]],
  [RealtimeEvents.NEED_ITEM_PURCHASED]: [["needs"]],
  [RealtimeEvents.NEED_EXPENSE_CREATED]: [["needs"], ["expenses"]],
  [RealtimeEvents.CHORE_CREATED]: [["chores"]],
  [RealtimeEvents.CHORE_UPDATED]: [["chores"]],
  [RealtimeEvents.CHORE_COMPLETED]: [["chores"]],
  [RealtimeEvents.CHORE_ASSIGNED]: [["chores"]],
  [RealtimeEvents.CHORE_DELETED]: [["chores"]],
  [RealtimeEvents.EXPENSE_CREATED]: [["expenses"]],
  [RealtimeEvents.EXPENSE_BALANCE_UPDATED]: [
    ["expenses", "balance"],
    ["expenses", "settlements"],
  ],
  [RealtimeEvents.PAYMENT_RECORDED]: [["payments"], ["expenses", "balance"]],
  [RealtimeEvents.NOTIFICATION_CREATED]: [["notifications"]],
  [RealtimeEvents.NOTIFICATION_READ]: [["notifications"]],
  [RealtimeEvents.NOTIFICATION_DELETED]: [["notifications"]],
  [RealtimeEvents.HOUSEHOLD_MEMBER_JOINED]: [["household", "me"]],
  [RealtimeEvents.HOUSEHOLD_MEMBER_LEFT]: [["household", "me"]],
  [RealtimeEvents.HOUSEHOLD_DELETED]: [["household", "me"]],
};
